package servent.message;

public enum MessageType {
    NEW_NODE, WELCOME, SORRY, UPDATE, POISON, TOKEN, PING, PONG, JOINED, UPDATE_CHORD, REMOVE, GET_REQUEST, GET_RESPONSE,ADD_FRIEND,ACCEPTED_FRIEND

}
